Job Orchestrator/src/objects/Job_Scheduler_Log__c.object
<CustomObject>
    <fields>
        <fullName>Job_Id__c</fullName>
        <description>Cron Id of the Scheduler</description>
        <label>Next Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Run_Time__c</fullName>
        <description>Time at which this instance ran.</description>
        <label>Run Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Instance</description>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Job Scheduler Log</label>
    <nameField>
        <displayFormat>JSLog-{0000}</displayFormat>
        <label>Job Scheduler Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Scheduler Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job Orchestrator/src/objects/JobSchedulerSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Frequency__c</fullName>
        <defaultValue>5</defaultValue>
        <description>Frequency in Minutes.</description>
        <inlineHelpText>Should be Integer Only</inlineHelpText>
        <label>Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>JobSchedulerSetting</label>
</CustomObject>

Job Orchestrator/src/classes/JobSchedulerTriggerHandler.cls
/**
 *	Summary: This class is working as a handler of trigger JobSchedulerTrigger
 *
 *	09 Jan 2014:	Dinesh M:	Created
**/

public with sharing class JobSchedulerTriggerHandler {
	static String errorLogStatus = 'Failed';	
	
	public static void onAfterInsert(List<Job_Scheduler_Log__c> createdLogList){
	
	System.debug(createdLogList);
		if(createdLogList[0].Status__c==errorLogStatus){
		
		
		
			JobSchedulerSetting__c j= JobSchedulerSetting__c.getInstance('Default');			
			Integer freq=Integer.ValueOf(j.Frequency__c);
			
			//DateTime dt=createdLogList[0].Run_Time__c.addMinutes(-freq);
			List<Job_Scheduler_Log__c> jLog=[Select Id,Status__c,Run_Time__c from Job_Scheduler_Log__c where Status__c=:errorLogStatus
								  			 order by  Run_Time__c Desc Limit 1];
					  			 
								  			 
			if(jLog.size()>0 && createdLogList[0].Run_Time__c.minute()-jLog[0].Run_Time__c.minute()==freq){
			
				System.debug('Aborting Job'==createdLogList[0].Job_Id__c);
				
				system.abortJob(createdLogList[0].Job_Id__c);			
			
			
			}
		
		}	
		
	}
	
}